Table entrees {
    id int [pk]
    name varchar
    price decimal
}

Table vegetables {
    id int [pk]
    name varchar
    price decimal
}

Table sides {
    id int [pk]
    name varchar
    price decimal
}

Table purchases {
    id int [pk]
    entreeId int [ref: > entrees.id]
    vegetableId int [ref: > vegetables.id]
    sideId int [ref: > sides.id]
}
